default_mode:     # Стандартный режим, загружается при старте игры
- 9               # Ширина поля
- 9               # Высота поля
- 10              # Кол-во бомб
modes:            # Режимы, в окне готовых настроек при выборе размера поля
  beginner:
  - 9             # Ширина поля
  - 9             # Высота поля
  - 10            # Кол-во бомб
  middle:
  - 16            # Ширина поля
  - 16            # Высота поля
  - 40            # Кол-во бомб
  pro:
  - 30            # Ширина поля
  - 16            # Высота поля
  - 99            # Кол-во бомб
presence: true    # Включение Discord Rich Presence
window_size:      # Размер окна игры при стандартном режиме. При изменении размера поля новый размер окна считается
- 328             # Ширина окна
- 408             # Высота окна
